FROM python:3.4

#RUN mkdir -p /usr/src/restore
#WORKDIR /usr/src/restore

#ONBUILD COPY requirements.txt /usr/src/restore/
#NBUILD RUN pip install --no-cache-dir -r requirements.txt

#ONBUILD COPY . /usr/src/restore

#RUN apt-get update && apt-get install -y \
#        gcc \
#        gettext \
#        mysql-client libmysqlclient-dev \
#        postgresql-client libpq-dev \
#        sqlite3 \
#    --no-install-recommends && rm -rf /var/lib/apt/lists/*

#EXPOSE 8000
#CMD ["python", "restore/manage.py", "runserver", "0.0.0.0:8000"]
